### ISSUE TITLE
Wrong path deduction

### ISSUE THREAD

**Issue by mfocko** [rebase-helper/rebase-helper#819] opened 2020-09-08 10:23 UTC
Hi, I've noticed during release of `packit` there's one failing test, but only in F33 and Rawhide.

I've checked on our side, paths seem to be set correctly. The path it tries to open looks like it has the path from root 2 times in a row and also macro? Could you have a look, please?

- Link to logs: https://jenkins-continuous-infra.apps.ci.centos.org/blue/rest/organizations/jenkins/pipelines/fedora-rawhide-pr-pipeline/runs/4676/nodes/176/log/?start=0
- can be reproduced on our side on current release (0.16.0) and also previous one with rawhide (or f33) image in docker

<details>
<summary>Snippet of the logs</summary>

```
  /usr/lib/python3.9/site-packages/packit/upstream.py:247: in get_specfile_version
      version = self.specfile.get_version()
  /usr/lib/python3.9/site-packages/packit/base_git.py:101: in specfile
      self._specfile = Specfile(
  /usr/lib/python3.9/site-packages/packit/specfile.py:53: in __init__
      super().__init__(path=str(path), sources_location=str(sources_dir))
  /usr/lib/python3.9/site-packages/rebasehelper/specfile.py:129: in __init__
      self.spc: rpm.spec = RpmHelper.get_rpm_spec(self.path, self.sources_location, self.predefined_macros)
  /usr/lib/python3.9/site-packages/rebasehelper/helpers/rpm_helper.py:205: in get_rpm_spec
      spec = cls.parse_spec(path)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

  cls = <class 'rebasehelper.helpers.rpm_helper.RpmHelper'>
  path = '/tmp/pytest-of-root/pytest-0/test_get_version_macro0/local_clone-upstream_git/beer.spec'
  flags = None

      @classmethod
      def parse_spec(cls, path, flags=None):
          with open(path, 'rb') as orig:
              with tempfile.NamedTemporaryFile() as tmp:
                  # remove BuildArch to workaround rpm bug
                  tmp.write(b''.join(l for l in orig.readlines() if not l.startswith(b'BuildArch')))
                  tmp.flush()
                  capturer = None
                  try:
                      with ConsoleHelper.Capturer(stderr=True) as capturer:
                          result = rpm.spec(tmp.name, flags) if flags is not None else rpm.spec(tmp.name)
                  except ValueError as e:
                      output = capturer.stderr.strip().split('\n') if capturer else []
                      if len(output) == 1:
                          output = output[0]
  >                   raise RebaseHelperError('Failed to parse SPEC file{0}'.format(
                          ': ' + str(output) if output else '')) from e
  E                   rebasehelper.exceptions.RebaseHelperError: Failed to parse SPEC file: ["python3: can't open file '/tmp/pytest-of-root/pytest-0/test_get_version_macro0/%SOURCE/tmp/pytest-of-root/pytest-0/test_get_version_macro0/local_clone-upstream_git/setup.py': [Errno 2] No such file or directory", 'error: line 6: Empty tag: Version:']

  /usr/lib/python3.9/site-packages/rebasehelper/helpers/rpm_helper.py:187: RebaseHelperError
```
</details>

```
rebasehelper.exceptions.RebaseHelperError: Failed to parse SPEC file: ["python3: can't open file '/tmp/pytest-of-root/pytest-0/test_get_version_macro0/%SOURCE/tmp/pytest-of-root/pytest-0/test_get_version_macro0/local_clone-upstream_git/setup.py': [Errno 2] No such file or directory", 'error: line 6: Empty tag: Version:']

[We create this file in tests]:
  /tmp/pytest-of-root/pytest-0/test_get_version_macro0/local_clone-upstream_git/setup.py
[It tries to parse this one]:
  /tmp/pytest-of-root/pytest-0/test_get_version_macro0/%SOURCE/tmp/pytest-of-root/pytest-0/test_get_version_macro0/local_clone-upstream_git/setup.py
```

**Comment by FrNecas** [comment] 2020-09-09 09:23
Hello @mfocko , thanks for the report. After some investigation, we found out that the issue is related to a change in RPM 4.16. The fix is trivial so while I was at it, I created a PR for packit that fixes the problem - see https://github.com/packit/packit/pull/958 for more information. I am closing this issue as it's not directly related to rebase-helper and the PR should fix the problem ;)

**Closed by FrNecas** 2020-09-09 09:23 UTC
