### ISSUE TITLE
Option for pushing, building changes officially in Git

### ISSUE THREAD

**Issue by phracek** [rebase-helper/rebase-helper#62] opened 2014-08-11 11:20 UTC
It would be good to provide an option who will copy updated patches, specfile and other stuff from rebase-helper-results directory to GIT tree.
- the option should add/remove changed/deleted files to GIT
- commit changes over user defined message
- build the package officially.

**Comment by nforro** [comment] 2017-05-25 15:21
Duplicate of issue #150.

**Closed** 2018-02-09 15:33 UTC
Labels: duplicate, enhancement, nice to have
